### ISSUE TITLE
No message body reader has been found for class com.docusign.esign.client.auth.OAuth$OAuthToken

### ISSUE THREAD

**Issue by ajesk** [SymphonyPlatformSolutions/symphony-api-client-java#214]
After updating our docusign dependency to 3.8.0 from 2.8.0 (we also attempted 2.9.0) I am finding that we are now seeing the title error popping up when making a request.

> [2020.09.14 11:54:02.230 [localhost] ERROR http-nio-8080-exec-9 JAXRSUtils:1807]  [GUID=3436fca3-aa37-43aa-87e9-47e199ca5d8a] No message body reader has been found for class com.docusign.esign.client.auth.OAuth$OAuthToken, ContentType: application/json;charset=utf-8
[2020.09.14 11:54:02.231 [localhost] ERROR http-nio-8080-exec-9 DocusignAuthenticationService:80]  [GUID=3436fca3-aa37-43aa-87e9-47e199ca5d8a] Unknown error getting docusign access token
javax.ws.rs.client.ResponseProcessingException: No message body reader has been found for class com.docusign.esign.client.auth.OAuth$OAuthToken, ContentType: application/json;charset=utf-8
	at org.apache.cxf.jaxrs.impl.ResponseImpl.reportMessageHandlerProblem(ResponseImpl.java:434) ~[cxf-rt-frontend-jaxrs-3.2.5.jar:3.2.5]
	at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:387) ~[cxf-rt-frontend-jaxrs-3.2.5.jar:3.2.5]

Nothing in the library call changed.

`apiClient.requestJWTUserToken(configuration.getIntegratorKey(), configuration.getUserId(), DEFAULT_SCOPES, configuration.getPrivateKey().getBytes(), JWT_TOKEN_TIMEOUT)`

While stepping through the execution of the auth I am seeing that the API itself returns a success response with the following (trimmed) block. 

> {"access_token":"itsasecretaccesstokensorrry","token_type":"Bearer","expires_in":3600}

Everything looks normal, but for some reason it is unable to map the JSON to the object after the request is made. Any suggestions or tweaks that might help alleviate this issue.

**Comment by ajesk** [comment]
If anything else is needed to identify potential issues let me know
